# Site wide configuration

title: "Alexander L. Hayes"
description: "Alexander L. Hayes &mdash; Health Informatics Ph.D. Student with the Proactive Health Informatics Group (ProHealth) at the School of Informatics, Computing, and Engineering (SICE) at Indiana University, Bloomington (IU)."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: https://hayesall.com
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Alexander L. Hayes
  email: alexander@batflyer.net
  twitter: alexanderlhayes
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:

# Collections

collections:
  classes:
    permalink: /teaching/:title/
    output: true

include:
  - .htaccess
  - _pages
  - ["_pages"]
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - vendor
