# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# variables are referenced with {{ site.email }} or {{ site.title }}

title: Alexander L. Hayes
email: alexander@batflyer.net
description: > # this means to ignore newlines until "baseurl:"
  Alexander L. Hayes is a Computer Science Ph.D. Student advised by Professor Sriraam
  Natarajan at the University of Texas at Dallas. Research interests are broadly in
  machine learning and knowledge representation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://batflyer.net" # the base hostname & protocol for your site
twitter_username: alexanderlhayes
github_username:  batflyer

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rogue

theme: minima
gems:
  - jekyll-feed
  - json
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /blog/:year/:month/:day/:title