# Site wide configuration

title: "hayesall.com"
description: "Alexander L. Hayes • Home • hayesall.com"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: https://hayesall.com
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from


# Site owner
owner:
  name: Alexander L. Hayes
  email: alexander@batflyer.net
  twitter: alexanderlhayes
  google:
    ad-client:
    ad-slot:
    analytics: UA-99296192-1
  bio: "Ph.D. Student at Indiana University Bloomington"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:

# Collections

collections:
  classes:
    permalink: /teaching/:title/
    output: true
  publications:
    permalink: /publications/:title/
    output: true
  software:
    permalink: /software/:title/
    output: true

include:
  - .htaccess
  - _pages
  - ["_pages"]
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - package-lock.json
  - spec
  - tmp
  - vendor
